services:
  postgres:
    image: postgres:17
    container_name: eshop-postgres
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d 
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 10
volumes:
  postgres_data:
