services:
  postgres:
    image: pgvector/pgvector:pg17 # Postgres 17 + pgvector extension
    container_name: eshop-postgres
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 10
  api:
    build:
      context: ./backend/e-shop
    container_name: eshop-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eshop
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME:-}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD:-}
      APP_MAIL_FROM: ${APP_MAIL_FROM:-E-Shop no-reply <no-reply@eshop.local>}
      APP_ACTIVATION_BASE_URL: ${APP_ACTIVATION_BASE_URL:-http://localhost:8080/api/auth/activate}
      APP_ACTIVATION_TOKEN_EXPIRATION_MINUTES: ${APP_ACTIVATION_TOKEN_EXPIRATION_MINUTES:-1440}
      STORAGE_MINIO_ENDPOINT: http://minio:9000
      STORAGE_MINIO_ACCESS_KEY: admin
      STORAGE_MINIO_SECRET_KEY: admin123
      STORAGE_MINIO_BUCKET: products
      STORAGE_MINIO_REGION: us-east-1
      STORAGE_MINIO_PUBLIC_URL: http://localhost:9000
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    restart: unless-stopped
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: eshop-minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data
    restart: unless-stopped
volumes:
  postgres_data:
  minio_data:
