services:
  postgres:
    image: postgres:17
    container_name: eshop-postgres
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d 
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 10

  postgres_test:
    image: postgres:17
    container_name: eshop-postgres-test
    environment:
      POSTGRES_DB: eshop_test
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: ./backend/e-shop
    container_name: eshop-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eshop
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
volumes:
  postgres_data:
  postgres_test_data:

