spring:
  config:
    import: optional:file:.env.properties
  datasource:
    url: jdbc:postgresql://localhost:5433/eshop
    username: app
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true # if DB already has tables
    locations: classpath:db/migration
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: "health"
storage:
  minio:
    endpoint: ${STORAGE_MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${STORAGE_MINIO_ACCESS_KEY:admin}
    secret-key: ${STORAGE_MINIO_SECRET_KEY:admin123}
    bucket: ${STORAGE_MINIO_BUCKET:products}
    region: ${STORAGE_MINIO_REGION:us-east-1}
    public-url: ${STORAGE_MINIO_PUBLIC_URL:http://localhost:9000}
app:
  base-url: /api/v1
  mail:
    from-address: ${APP_MAIL_FROM:E-Shop no-reply <no-reply@eshop.local>}
  auth:
    activation:
      base-url: ${APP_ACTIVATION_BASE_URL:http://localhost:8080/api/auth/activate}
      token-expiration-minutes: ${APP_ACTIVATION_TOKEN_EXPIRATION_MINUTES:1440}
    password-reset:
      token-expiration-minutes: ${APP_PASSWORD_RESET_TOKEN_EXPIRATION_MINUTES:15}
  jwt:
    secret: ${JWT_SECRET:b@N3OeiLg$!bG9l!$^FHS*D(!*jasd(!@FHASD}
    access-expiration-seconds: 360000
    refresh-expiration-seconds: 1296000
  payment:
    vnpay:
      version: ${VNPAY_VERSION:2.1.0}
      command: ${VNPAY_COMMAND:pay}
      tmn-code: ${VNPAY_TMN_CODE:82TFXA73}
      hash-secret: ${VNPAY_HASH_SECRET:EVPSPUGCI0D5M0RP8KTVHHUAP29XNWLK}
      api-url: ${VNPAY_API_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
      return-url: ${VNPAY_RETURN_URL:http://localhost:5173/payment-result}
      #      ipn-url: ${VNPAY_IPN_URL:http://localhost:8080} 
      locale: ${VNPAY_LOCALE:vn}
      order-type: ${VNPAY_ORDER_TYPE:other}
      order-info-prefix: ${VNPAY_ORDER_INFO_PREFIX:E-Shop Order}
      expire-after-minutes: ${VNPAY_EXPIRE_AFTER_MINUTES:15}
recommendation:
  base-url: ${RECOMMENDER_BASE_URL:http://localhost:8000}
  enabled: true
  connect-timeout: 2s
  read-timeout: 3s
